spring.application.name=gatherscholar

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/gatherscholar_db}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:javaismynightmare}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true