spring.application.name=gatherscholar

spring.datasource.url=jdbc:postgresql://localhost:5432/gatherscholar_db
spring.datasource.username=postgres
spring.datasource.password=javaismynightmare

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-plateform=org.hibernate.dialect.PostgreSQLDialect