server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/gatherscholar
spring.datasource.username=postgres
spring.datasource.password=javaismynightmare

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true